# Numpy
- [Official Documents: numpy.org](https://numpy.org/doc/stable/reference/index.html)
- [repository: github.com](https://github.com/numpy/numpy)

In [1]:
import numpy as np

## Replacement

In [4]:
a = np.array(range(40), 'float').reshape((1,5,8))
a[0,2:4, 3:6] = np.nan
print(a)

[[[ 0.  1.  2.  3.  4.  5.  6.  7.]
  [ 8.  9. 10. 11. 12. 13. 14. 15.]
  [16. 17. 18. nan nan nan 22. 23.]
  [24. 25. 26. nan nan nan 30. 31.]
  [32. 33. 34. 35. 36. 37. 38. 39.]]]


In [5]:
a.__str__()

'[[[ 0.  1.  2.  3.  4.  5.  6.  7.]\n  [ 8.  9. 10. 11. 12. 13. 14. 15.]\n  [16. 17. 18. nan nan nan 22. 23.]\n  [24. 25. 26. nan nan nan 30. 31.]\n  [32. 33. 34. 35. 36. 37. 38. 39.]]]'

In [ ]:
a = np.array(range(24)).reshape((2,3,4))
print(a)

In [ ]:
a_target = []
for idx, ai in enumerate(a):
    a_target.append(ai)

In [ ]:
np.array(a_target)

In [ ]:
# replace all value
a[:] = np.nan
a

In [ ]:
# replace specific value
a = np.array(range(40), 'float').reshape((2,4,5))
a[(a == 10) | (a == 32)] = np.nan
a

In [ ]:
# replace nan value with clumn wise different value
# https://stackoverflow.com/a/18689440/
a = np.array(range(20), 'float').reshape((5,4))
a[1:3, 2:4] = np.nan
print(a)
replace_values = [100, 101, 102, 103]
print(replace_values)
idxs = np.where(np.isnan(a))
a[idxs] = np.take(replace_values, idxs[1])
print(a)

## Append

In [ ]:
a_0 = []
a_1 = np.array(range(12)).reshape((3,4))
a_0.append(a_1)
print(a_0)
a_2 = np.array(range(100,112)).reshape((3,4))
a_0.append(a_2)
print(a_0)
print(np.array(a_0).shape)

## where

In [204]:
print(a)
print(channel_max)
a > channel_max

[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]

 [[24. 25. 26. 27.]
  [28. 29. 30. 31.]
  [32. 33. 34. 35.]]]
[[[10]]

 [[10]]

 [[10]]]


array([[[False, False, False, False],
        [False, False, False, False],
        [False, False, False,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]])

In [210]:
# channel_min = np.resize([1, 16, 26], (3,1,1))
# channel_max = np.resize([10, 21, 31], (3,1,1))
# channel_min = np.resize(10, (3,1,1))
# channel_max = np.resize(20, (3,1,1))
channel_min = None
channel_max = np.resize(20, (3,1,1))

a = np.array(range(36)).reshape((3,3,4))
a = a.astype('float32')
a = np.where((channel_min<a)&(a<channel_max), a, np.nan )
a[1:2,1:3,1:2] = np.nan
a

TypeError: '>' not supported between instances of 'float' and 'NoneType'

In [5]:
channel_max = np.resize(20, (3,1,1)).astype('float32')
channel_max.dtype

dtype('float32')

## Dilation

In [41]:
from scipy.ndimage import binary_dilation, generate_binary_structure 

In [38]:
# a = np.zeros((3,10,11), dtype='bool')
a = np.zeros((3,10,11), dtype='bool')
a[0, 1:4, 3:6] = True
print(a)

[[[False False False False False False False False False False False]
  [False False False  True  True  True False False False False False]
  [False False False  True  True  True False False False False False]
  [False False False  True  True  True False False False False False]
  [False False False False False False False False False False False]
  [False False False False False False False False False False False]
  [False False False False False False False False False False False]
  [False False False False False False False False False False False]
  [False False False False False False False False False False False]
  [False False False False False False False False False False False]]

 [[False False False False False False False False False False False]
  [False False False False False False False False False False False]
  [False False False False False False False False False False False]
  [False False False False False False False False False False False]
  [False False Fal

In [39]:
print(binary_dilation(a, iterations=2))

[[[False False  True  True  True  True  True False False False False]
  [False  True  True  True  True  True  True  True False False False]
  [False  True  True  True  True  True  True  True False False False]
  [False  True  True  True  True  True  True  True False False False]
  [False False  True  True  True  True  True False False False False]
  [False False False  True  True  True False False False False False]
  [False False False False False False False False False False False]
  [False False False False False False False False False False False]
  [False False False False False False False False False False False]
  [False False False False False False False False False False False]]

 [[False False False  True  True  True False False False False False]
  [False False  True  True  True  True  True False False False False]
  [False False  True  True  True  True  True False False False False]
  [False False  True  True  True  True  True False False False False]
  [False False Fal

In [78]:
struct = generate_binary_structure(a.ndim, 3)
print(struct)

[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]]]


In [79]:
print(binary_dilation(a, iterations=2, structure=struct))

[[[False  True  True  True  True  True  True  True False False False]
  [False  True  True  True  True  True  True  True False False False]
  [False  True  True  True  True  True  True  True False False False]
  [False  True  True  True  True  True  True  True False False False]
  [False  True  True  True  True  True  True  True False False False]
  [False  True  True  True  True  True  True  True False False False]
  [False False False False False False False False False False False]
  [False False False False False False False False False False False]
  [False False False False False False False False False False False]
  [False False False False False False False False False False False]]

 [[False  True  True  True  True  True  True  True False False False]
  [False  True  True  True  True  True  True  True False False False]
  [False  True  True  True  True  True  True  True False False False]
  [False  True  True  True  True  True  True  True False False False]
  [False  True  Tr

## channel selection

In [84]:
a = np.array(range(36)).reshape((3,3,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [192]:
c = 1
print(a.dtype)

float32


In [190]:
l = 1
np.resize(np.array(l), (3,1,1))

#np.array(l).reshape(3,1,1)

array([[[1]],

       [[1]],

       [[1]]])

## normalize by channel

In [ ]:
def znorm_by_channel(array:np.ndarray) -> np.ndarray:
    """ z-normalization of each channel of 3D numpy array
    
    Args:
        array:
            3 dimentional numpy array which is channel first format.
    Returns:
        tuple of normalized array, list of original mean values of each channel,
        and list of original standard deviations of each channel.
    Example:
        >>> a = np.array([[[    0.,  1., np.nan, np.nan],
        ...                [    4.,  5.,     6.,     7.],
        ...                [    8.,  9.,    10.,    11.]],
        ...               [[np.nan, 13.,    14.,    15.],
        ...                [np.nan, 17.,    18.,    19.],
        ...                [np.nan, 21.,    22.,    23.]]])
        ...
        >>> znorm_by_channel()
        ... (array([[[-1.75435174, -1.46675309,         nan,         nan],
        ...          [-0.60395716, -0.31635851, -0.02875986,  0.25883878],
        ...          [ 0.54643743,  0.83403607,  1.12163472,  1.40923337]],
        ...  
        ...         [[        nan, -1.48522127, -1.18817702, -0.89113276],
        ...          [        nan, -0.29704425,  0.        ,  0.29704425],
        ...          [        nan,  0.89113276,  1.18817702,  1.48522127]]]),
        ...  array([ 6.1, 18. ]),
        ...  array([3.47706773, 3.36650165]))
    """
    if array.ndim != 3:
        raise ValueError(f'Input array need to be 3D, not {array.ndim}D.')
    means = np.nanmean(array, axis=(1,2))
    stds = np.nanstd(array, axis=(1,2))
    normalized_array = (array - means[:, None,  None])/(stds[:, None,  None] + 1e-7)
    return normalized_array, means, stds

array = np.array(range(24), 'float').reshape((2,3,4))
array[0, 0, 2:] = np.nan
array[1, :, 0] = np.nan
print(array)
znorm_by_channel(array)


In [129]:
a = np.array([[    0.,  1., np.nan, np.nan],
               [    4.,  5.,     6.,     7.],
               [    8.,  9.,    10.,    11.]])
a.ndim
znorm_by_channel(a)

NameError: name 'znorm_by_channel' is not defined

### linear normalization


In [166]:
a = np.array(range(36), dtype='float32').reshape((3,3,4))
a[2, 2:3, 1:2] = np.nan
print(a)
mx = np.nanmax(a, axis=(1,2)).reshape(a.shape[0],1,1)
mn = np.nanmin(a, axis=(1,2)).reshape(a.shape[0],1,1)
(a - mn)/(mx - mn)

[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]

 [[24. 25. 26. 27.]
  [28. 29. 30. 31.]
  [32. nan 34. 35.]]]


array([[[0.        , 0.09090909, 0.18181819, 0.27272728],
        [0.36363637, 0.45454547, 0.54545456, 0.6363636 ],
        [0.72727275, 0.8181818 , 0.90909094, 1.        ]],

       [[0.        , 0.09090909, 0.18181819, 0.27272728],
        [0.36363637, 0.45454547, 0.54545456, 0.6363636 ],
        [0.72727275, 0.8181818 , 0.90909094, 1.        ]],

       [[0.        , 0.09090909, 0.18181819, 0.27272728],
        [0.36363637, 0.45454547, 0.54545456, 0.6363636 ],
        [0.72727275,        nan, 0.90909094, 1.        ]]], dtype=float32)

In [149]:
np.arange(3.0)

array([0., 1., 2.])

# channel_first to channel_last

In [ ]:
a = np.array(range(24), 'float').reshape((2,3,4))
print(a.shape)
print(a)

b = np.moveaxis(a, -1, 0)

print(b)
print(b.shape)

In [ ]:
# check isin
a = np.array(range(12))
print(np.isin(a, [4,5]))
print(np.isin(a, None))


In [13]:
a = np.array(range(12)).reshape((3,4))
a.ndim

2

In [14]:
np.array([a]).ndim

3

In [16]:
a = np.array(range(24)).reshape((2,3,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [18]:
a[:] = 0
a

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])