# Numpy
- [Official Documents: numpy.org](https://numpy.org/doc/stable/reference/index.html)
- [repository: github.com](https://github.com/numpy/numpy)

In [2]:
import numpy as np

## Replacement

In [2]:
a = np.array(range(40), 'float').reshape((1,5,8))
a[0,2:4, 3:6] = np.nan
print(a)

[[[ 0.  1.  2.  3.  4.  5.  6.  7.]
  [ 8.  9. 10. 11. 12. 13. 14. 15.]
  [16. 17. 18. nan nan nan 22. 23.]
  [24. 25. 26. nan nan nan 30. 31.]
  [32. 33. 34. 35. 36. 37. 38. 39.]]]


slice(0, (2, 4), (3, 6))

In [25]:
a = np.array(range(40), 'float').reshape((1,5,8))
print(a)
my_slice1 = slice(None, None, None)
my_slice2 = slice(2, 4, None)
my_slice3 = slice(3, 6, None)
print(a[0, my_slice2, my_slice3])


[[[ 0.  1.  2.  3.  4.  5.  6.  7.]
  [ 8.  9. 10. 11. 12. 13. 14. 15.]
  [16. 17. 18. 19. 20. 21. 22. 23.]
  [24. 25. 26. 27. 28. 29. 30. 31.]
  [32. 33. 34. 35. 36. 37. 38. 39.]]]
[[19. 20. 21.]
 [27. 28. 29.]]


In [5]:
a = np.array(range(24)).reshape((2,3,4))
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [6]:
a_target = []
for idx, ai in enumerate(a):
    a_target.append(ai)

In [7]:
np.array(a_target)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [8]:
# replace all value
a[:] = np.nan
a

array([[[-9223372036854775808, -9223372036854775808,
         -9223372036854775808, -9223372036854775808],
        [-9223372036854775808, -9223372036854775808,
         -9223372036854775808, -9223372036854775808],
        [-9223372036854775808, -9223372036854775808,
         -9223372036854775808, -9223372036854775808]],

       [[-9223372036854775808, -9223372036854775808,
         -9223372036854775808, -9223372036854775808],
        [-9223372036854775808, -9223372036854775808,
         -9223372036854775808, -9223372036854775808],
        [-9223372036854775808, -9223372036854775808,
         -9223372036854775808, -9223372036854775808]]])

In [9]:
# replace specific value
a = np.array(range(40), 'float').reshape((2,4,5))
a[(a == 10) | (a == 32)] = np.nan
a

array([[[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [nan, 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]],

       [[20., 21., 22., 23., 24.],
        [25., 26., 27., 28., 29.],
        [30., 31., nan, 33., 34.],
        [35., 36., 37., 38., 39.]]])

In [10]:
# replace nan value with clumn wise different value
# https://stackoverflow.com/a/18689440/
a = np.array(range(20), 'float').reshape((5,4))
a[1:3, 2:4] = np.nan
print(a)
replace_values = [100, 101, 102, 103]
print(replace_values)
idxs = np.where(np.isnan(a))
a[idxs] = np.take(replace_values, idxs[1])
print(a)

[[ 0.  1.  2.  3.]
 [ 4.  5. nan nan]
 [ 8.  9. nan nan]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]]
[100, 101, 102, 103]
[[  0.   1.   2.   3.]
 [  4.   5. 102. 103.]
 [  8.   9. 102. 103.]
 [ 12.  13.  14.  15.]
 [ 16.  17.  18.  19.]]


## Append

In [11]:
a_0 = []
a_1 = np.array(range(12)).reshape((3,4))
a_0.append(a_1)
print(a_0)
a_2 = np.array(range(100,112)).reshape((3,4))
a_0.append(a_2)
print(a_0)
print(np.array(a_0).shape)

[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])]
[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111]])]
(2, 3, 4)


## Listへの変換 

In [12]:
a = np.array(range(10))
list(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## where

## Dilation

In [68]:
from scipy.ndimage import binary_dilation, binary_erosion, generate_binary_structure, iterate_structure

In [69]:
# a = np.zeros((3,10,11), dtype='bool')
a = np.zeros((3,10,11), dtype='bool')
a[0, 1:4, 3:6] = True
print(a)

[[[False False False False False False False False False False False]
  [False False False  True  True  True False False False False False]
  [False False False  True  True  True False False False False False]
  [False False False  True  True  True False False False False False]
  [False False False False False False False False False False False]
  [False False False False False False False False False False False]
  [False False False False False False False False False False False]
  [False False False False False False False False False False False]
  [False False False False False False False False False False False]
  [False False False False False False False False False False False]]

 [[False False False False False False False False False False False]
  [False False False False False False False False False False False]
  [False False False False False False False False False False False]
  [False False False False False False False False False False False]
  [False False Fal

In [72]:
a2 = binary_dilation(a, iterations=2)
print(a2)

[[[False False  True  True  True  True  True False False False False]
  [False  True  True  True  True  True  True  True False False False]
  [False  True  True  True  True  True  True  True False False False]
  [False  True  True  True  True  True  True  True False False False]
  [False False  True  True  True  True  True False False False False]
  [False False False  True  True  True False False False False False]
  [False False False False False False False False False False False]
  [False False False False False False False False False False False]
  [False False False False False False False False False False False]
  [False False False False False False False False False False False]]

 [[False False False  True  True  True False False False False False]
  [False False  True  True  True  True  True False False False False]
  [False False  True  True  True  True  True False False False False]
  [False False  True  True  True  True  True False False False False]
  [False False Fal

In [74]:
print(binary_erosion(a2))

[[[False False False False False False False False False False False]
  [False False False False False False False False False False False]
  [False False False False False False False False False False False]
  [False False False False False False False False False False False]
  [False False False False False False False False False False False]
  [False False False False False False False False False False False]
  [False False False False False False False False False False False]
  [False False False False False False False False False False False]
  [False False False False False False False False False False False]
  [False False False False False False False False False False False]]

 [[False False False False False False False False False False False]
  [False False False  True  True  True False False False False False]
  [False False False  True  True  True False False False False False]
  [False False False  True  True  True False False False False False]
  [False False Fal

In [87]:
struct = generate_binary_structure(2, 1)
struct = iterate_structure(struct, 2)
print(struct)

[[False False  True False False]
 [False  True  True  True False]
 [ True  True  True  True  True]
 [False  True  True  True False]
 [False False  True False False]]


In [29]:
struct = generate_binary_structure(a.ndim, 1)
print(struct)

[[[False False False]
  [False  True False]
  [False False False]]

 [[False  True False]
  [ True  True  True]
  [False  True False]]

 [[False False False]
  [False  True False]
  [False False False]]]


In [82]:
print(binary_dilation(a, iterations=1, structure=struct))

[[[False  True  True  True  True  True  True  True False False False]
  [False  True  True  True  True  True  True  True False False False]
  [False  True  True  True  True  True  True  True False False False]
  [False  True  True  True  True  True  True  True False False False]
  [False  True  True  True  True  True  True  True False False False]
  [False  True  True  True  True  True  True  True False False False]
  [False False False False False False False False False False False]
  [False False False False False False False False False False False]
  [False False False False False False False False False False False]
  [False False False False False False False False False False False]]

 [[False  True  True  True  True  True  True  True False False False]
  [False  True  True  True  True  True  True  True False False False]
  [False  True  True  True  True  True  True  True False False False]
  [False  True  True  True  True  True  True  True False False False]
  [False  True  Tr

## channel selection

In [22]:
a = np.array(range(36)).reshape((3,3,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [23]:
c = 1
print(a.dtype)

int64


In [24]:
l = 1
np.resize(np.array(l), (3,1,1))

#np.array(l).reshape(3,1,1)

array([[[1]],

       [[1]],

       [[1]]])

## normalize by channel

In [25]:
def znorm_by_channel(array:np.ndarray) -> np.ndarray:
    """ z-normalization of each channel of 3D numpy array
    
    Args:
        array:
            3 dimentional numpy array which is channel first format.
    Returns:
        tuple of normalized array, list of original mean values of each channel,
        and list of original standard deviations of each channel.
    Example:
        >>> a = np.array([[[    0.,  1., np.nan, np.nan],
        ...                [    4.,  5.,     6.,     7.],
        ...                [    8.,  9.,    10.,    11.]],
        ...               [[np.nan, 13.,    14.,    15.],
        ...                [np.nan, 17.,    18.,    19.],
        ...                [np.nan, 21.,    22.,    23.]]])
        ...
        >>> znorm_by_channel()
        ... (array([[[-1.75435174, -1.46675309,         nan,         nan],
        ...          [-0.60395716, -0.31635851, -0.02875986,  0.25883878],
        ...          [ 0.54643743,  0.83403607,  1.12163472,  1.40923337]],
        ...  
        ...         [[        nan, -1.48522127, -1.18817702, -0.89113276],
        ...          [        nan, -0.29704425,  0.        ,  0.29704425],
        ...          [        nan,  0.89113276,  1.18817702,  1.48522127]]]),
        ...  array([ 6.1, 18. ]),
        ...  array([3.47706773, 3.36650165]))
    """
    if array.ndim != 3:
        raise ValueError(f'Input array need to be 3D, not {array.ndim}D.')
    means = np.nanmean(array, axis=(1,2))
    stds = np.nanstd(array, axis=(1,2))
    normalized_array = (array - means[:, None,  None])/(stds[:, None,  None] + 1e-7)
    return normalized_array, means, stds

array = np.array(range(24), 'float').reshape((2,3,4))
array[0, 0, 2:] = np.nan
array[1, :, 0] = np.nan
print(array)
znorm_by_channel(array)


[[[ 0.  1. nan nan]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[nan 13. 14. 15.]
  [nan 17. 18. 19.]
  [nan 21. 22. 23.]]]


(array([[[-1.75435174, -1.46675309,         nan,         nan],
         [-0.60395716, -0.31635851, -0.02875986,  0.25883878],
         [ 0.54643743,  0.83403607,  1.12163472,  1.40923337]],
 
        [[        nan, -1.48522127, -1.18817702, -0.89113276],
         [        nan, -0.29704425,  0.        ,  0.29704425],
         [        nan,  0.89113276,  1.18817702,  1.48522127]]]),
 array([ 6.1, 18. ]),
 array([3.47706773, 3.36650165]))

In [27]:
a = np.array([[    0.,  1., np.nan, np.nan],
               [    4.,  5.,     6.,     7.],
               [    8.,  9.,    10.,    11.]])
a.ndim
# znorm_by_channel(a) # -> ERROR

2

### linear normalization


In [28]:
a = np.array(range(36), dtype='float32').reshape((3,3,4))
a[2, 2:3, 1:2] = np.nan
print(a)
mx = np.nanmax(a, axis=(1,2)).reshape(a.shape[0],1,1)
mn = np.nanmin(a, axis=(1,2)).reshape(a.shape[0],1,1)
(a - mn)/(mx - mn)

[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]

 [[24. 25. 26. 27.]
  [28. 29. 30. 31.]
  [32. nan 34. 35.]]]


array([[[0.        , 0.09090909, 0.18181819, 0.27272728],
        [0.36363637, 0.45454547, 0.54545456, 0.6363636 ],
        [0.72727275, 0.8181818 , 0.90909094, 1.        ]],

       [[0.        , 0.09090909, 0.18181819, 0.27272728],
        [0.36363637, 0.45454547, 0.54545456, 0.6363636 ],
        [0.72727275, 0.8181818 , 0.90909094, 1.        ]],

       [[0.        , 0.09090909, 0.18181819, 0.27272728],
        [0.36363637, 0.45454547, 0.54545456, 0.6363636 ],
        [0.72727275,        nan, 0.90909094, 1.        ]]], dtype=float32)

In [29]:
np.arange(3.0)

array([0., 1., 2.])

## channel_first to channel_last

In [30]:
a = np.array(range(24), 'float').reshape((2,3,4))
print(a.shape)
print(a)

b = np.moveaxis(a, -1, 0)

print(b)
print(b.shape)

(2, 3, 4)
[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]]
[[[ 0.  4.  8.]
  [12. 16. 20.]]

 [[ 1.  5.  9.]
  [13. 17. 21.]]

 [[ 2.  6. 10.]
  [14. 18. 22.]]

 [[ 3.  7. 11.]
  [15. 19. 23.]]]
(4, 2, 3)


In [31]:
# check isin
a = np.array(range(12))
print(np.isin(a, [4,5]))
print(np.isin(a, None))


[False False False False  True  True False False False False False False]
[False False False False False False False False False False False False]


In [32]:
a = np.array(range(12)).reshape((3,4))
a.ndim

2

In [33]:
np.array([a]).ndim

3

In [34]:
a = np.array(range(24)).reshape((2,3,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [35]:
a[:] = 0
a

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

## cummrative array

In [36]:
a = np.random.randint(4, size=10)
print(a)
# cumulative sum 
print(np.cumsum(a))
# cumulative sum from tail
print(np.flip(np.cumsum(np.flip(a))))

[3 1 2 1 1 2 3 3 0 2]
[ 3  4  6  7  8 10 13 16 16 18]
[18 15 14 12 11 10  8  5  2  2]


In [37]:
np.flip(np.array(range(10)))

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## diff
https://numpy.org/doc/stable/reference/generated/numpy.diff.html

In [38]:
a = np.random.randint(10, size=10)
print(a)
print(np.diff(a))

[3 0 4 8 3 6 6 3 8 4]
[-3  4  4 -5  3  0 -3  5 -4]


## median values of array

In [39]:
a = np.random.randint(1, 4, size=11)
bin_edge = np.cumsum(a)
print(bin_edge)
bin_width = np.diff(bin_edge)
print(bin_width)
bin_center = bin_edge[:-1] + (bin_width/2)
print(bin_center)

[ 3  5  6  8  9 12 13 15 18 20 23]
[2 1 2 1 3 1 2 3 2 3]
[ 4.   5.5  7.   8.5 10.5 12.5 14.  16.5 19.  21.5]


## RMSE over pixels

In [147]:
array_true = np.random.randint(0,10, 24).reshape((2,3,4))
array_pred = np.random.randint(0,10, 24).reshape((2,3,4))


In [148]:
print(array_true)

[[[8 5 3 0]
  [5 8 9 3]
  [9 8 9 8]]

 [[0 3 3 7]
  [9 9 9 7]
  [8 2 3 1]]]


In [52]:
def rmse_per_pixel():
    pass

In [55]:
array_true

array([[[0.37959857, 0.29042997, 0.31519026],
        [0.22883214, 0.02752307, 0.46667506],
        [0.47825642, 0.55466289, 0.37318111],
        [0.36813224, 0.4294124 , 0.75613597]],

       [[0.25844644, 0.02382232, 0.00773682],
        [0.50260891, 0.73809711, 0.09704421],
        [0.78378708, 0.70374521, 0.61378668],
        [0.12690163, 0.05702612, 0.56630808]],

       [[0.67261523, 0.7709724 , 0.32339138],
        [0.00192027, 0.39799333, 0.45241485],
        [0.22163431, 0.52614861, 0.88229942],
        [0.13846813, 0.78078311, 0.04942754]],

       [[0.12952159, 0.05179714, 0.21366357],
        [0.46824105, 0.83784501, 0.49210675],
        [0.67240911, 0.72212739, 0.06575058],
        [0.08070713, 0.97442832, 0.75593945]],

       [[0.88492479, 0.47760685, 0.64047963],
        [0.77548215, 0.96010126, 0.67784   ],
        [0.76970726, 0.84978645, 0.44241832],
        [0.27933383, 0.30285193, 0.84552135]]])

In [132]:
a = np.array(range(12)).reshape((1,3,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [133]:
b = a *2
b

array([[[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22]]])

In [134]:
a.shape[1:3]

(3, 4)

In [149]:
from sklearn.metrics import mean_squared_error
def rmse_raster_arrays(arrays_true:np.ndarray,
                       arrays_pred:np.ndarray,
                       axis='pixel') -> np.ndarray:
    """Calculate RMSE from 3D arrays
    
    Args:
        arrays_true:
            Ground truth (correct) target values with 3D Numpy array
        array_pred:
            Estimated target values with same shape of arrays_true
        axis:
            'pixel' or 'layer'. 'pixel' returns rmse values at each pixels
            with same shape array with input arrays.
            'layer' returns rmse values of each layer. Length will be
            arrays_true[0]
    Returns:
        RMSE values of each pixel or layer.
    """
    if arrays_true.ndim != 3:
        raise ValueError(f'arrays needs to 3D array. Not {arrays_true.ndim}')
    if arrays_true.shape != arrays_pred.shape:
        raise ValueError(f'arrays_true shape {arrays_true.shape} and '
                         f'arrays_pred shape {arrays_pred.shape} must be same.')

    if axis == 'pixel':
        y_true = arrays_true.reshape(arrays_true.shape[0], -1)
        y_pred = arrays_pred.reshape(arrays_pred.shape[0], -1)
        
        return np.sqrt(mean_squared_error(y_true,
                                          y_pred,
                                          multioutput='raw_values')
                       .reshape(arrays_true.shape[1:3]))
    
    if axis == 'layer':
        y_true = (arrays_true
                  .transpose((1,2,0))
                  .reshape(-1, arrays_true.shape[0]))
        y_pred = (arrays_pred
                  .transpose((1,2,0))
                  .reshape(-1, arrays_pred.shape[0]))

        return np.sqrt(mean_squared_error(y_true,
                                          y_pred,
                                          multioutput='raw_values'))

out = rmse_raster_arrays(arrays_true=a,
                         arrays_pred=b,
                        axis='layer')
out

array([6.49358658])

In [105]:
out

array([ 6.49358658, 17.83722699, 29.70129066, 41.6433268 , 53.61125504])

## Mask

In [35]:
a = np.random.randint(0,10,40, dtype='int32').reshape((5,8))
b = np.random.randint(0,10,40, dtype='int32').reshape((5,8))
print(a)
print(b)

[[9 4 5 3 2 4 6 6]
 [5 4 4 5 4 5 9 3]
 [1 7 9 8 2 0 9 2]
 [8 6 5 2 0 8 9 7]
 [5 3 1 8 6 8 7 7]]
[[1 6 6 1 6 1 4 1]
 [4 3 3 5 5 0 9 7]
 [0 1 4 1 6 4 6 8]
 [4 9 4 2 0 4 4 4]
 [6 5 5 6 8 8 2 5]]


In [36]:
a_masked = np.ma.array(data=a, mask=(a<5))
b_masked = np.ma.array(data=b, mask=(b<5))
print(a_masked)
print(b_masked)

[[9 -- 5 -- -- -- 6 6]
 [5 -- -- 5 -- 5 9 --]
 [-- 7 9 8 -- -- 9 --]
 [8 6 5 -- -- 8 9 7]
 [5 -- -- 8 6 8 7 7]]
[[-- 6 6 -- 6 -- -- --]
 [-- -- -- 5 5 -- 9 7]
 [-- -- -- -- 6 -- 6 8]
 [-- 9 -- -- -- -- -- --]
 [6 5 5 6 8 8 -- 5]]


In [25]:
type(float(a_masked.mean()))

float

In [37]:
out_array = a_masked.data
out_array[a_masked.mask] = 0
out_array

array([[9, 0, 5, 0, 0, 0, 6, 6],
       [5, 0, 0, 5, 0, 5, 9, 0],
       [0, 7, 9, 8, 0, 0, 9, 0],
       [8, 6, 5, 0, 0, 8, 9, 7],
       [5, 0, 0, 8, 6, 8, 7, 7]], dtype=int32)

In [48]:
a_masked[a_masked > 7] = 0
a_masked

masked_array(
  data=[[7, 0, 5, --, 0, 5, 5, 0],
        [--, --, --, 7, 6, --, 0, --],
        [0, --, 7, 7, --, --, --, 0],
        [--, --, --, 0, 7, 6, 5, --],
        [--, --, 6, 7, 0, --, 7, 5]],
  mask=[[False, False, False,  True, False, False, False, False],
        [ True,  True,  True, False, False,  True, False,  True],
        [False,  True, False, False,  True,  True,  True, False],
        [ True,  True,  True, False, False, False, False,  True],
        [ True,  True, False, False, False,  True, False, False]],
  fill_value=999999,
  dtype=int32)

In [67]:
a_masked

masked_array(
  data=[[8, 9, 8, --, --, 9, 7, 7],
        [6, --, --, 6, --, --, 8, --],
        [8, --, --, 5, --, --, --, 5],
        [--, 8, --, --, 5, --, 7, 5],
        [--, --, 7, 9, --, --, --, 7]],
  mask=[[False, False, False,  True,  True, False, False, False],
        [False,  True,  True, False,  True,  True, False,  True],
        [False,  True,  True, False,  True,  True,  True, False],
        [ True, False,  True,  True, False,  True, False, False],
        [ True,  True, False, False,  True,  True,  True, False]],
  fill_value=999999,
  dtype=int32)

In [71]:
a = np.array(range(4), dtype='float32')
b = np.array(range(4), dtype='int8')
(a + b).dtype

dtype('float32')

In [63]:
print(a_masked)
print(b_masked)
print(~a_masked.mask & ~b_masked.mask)

[[8 9 8 -- -- 9 7 7]
 [6 -- -- 6 -- -- 8 --]
 [8 -- -- 5 -- -- -- 5]
 [-- 8 -- -- 5 -- 7 5]
 [-- -- 7 9 -- -- -- 7]]
[[-- -- 8 -- 7 5 5 --]
 [6 9 -- 6 -- -- 7 5]
 [7 5 9 -- -- 7 8 --]
 [-- 6 5 6 -- -- -- --]
 [-- -- 7 6 -- -- -- --]]
[[False False  True False False  True  True False]
 [ True False False  True False False  True False]
 [ True False False False False False False False]
 [False  True False False False False False False]
 [False False  True  True False False False False]]


In [60]:
a_masked.mask

array([[False, False, False,  True,  True, False, False, False],
       [False,  True,  True, False,  True,  True, False,  True],
       [False,  True,  True, False,  True,  True,  True, False],
       [ True, False,  True,  True, False,  True, False, False],
       [ True,  True, False, False,  True,  True,  True, False]])

In [61]:
a_masked.mask

array([[False, False, False,  True,  True, False, False, False],
       [False,  True,  True, False,  True,  True, False,  True],
       [False,  True,  True, False,  True,  True,  True, False],
       [ True, False,  True,  True, False,  True, False, False],
       [ True,  True, False, False,  True,  True,  True, False]])

## Percentile

In [22]:
a = np.random.randint(0, 1000, 100*100).reshape((1, 100, 100))
np.percentile(a, 10)

101.0

## Bool

In [32]:
a = np.array([0,1,2, np.nan])
print(a.dtype == 'float64')
print(a < 1)
print((a >= 1).dtype)

True
[ True False False False]
bool


In [34]:
a = np.array([True, False, False, True])
b = np.array([True, True, False, False])
a & b

array([ True, False, False, False])

In [59]:
a = np.array([True, True, True, True, True])
b = np.array([1, 2, 0, -1, 3])
c = np.array([1, 2, 0, -1, 3])
print(b)
print(a & b.astype('bool'))
print(a & b)

[ 1  2  0 -1  3]
[ True  True False  True  True]
[1 0 0 1 1]


In [65]:
a = np.array([3,2,1,0,-1,-2])
b = np.array([1,0,1,0, 1, 0])
print(a & b)
print((a < b).astype('int'))

[1 0 1 0 1 0]
[0 0 0 0 1 1]


In [105]:
a = np.array(range(5))
b = np.array([1,0,0,1,1]).astype('bool')
a[b]

array([0, 3, 4])

## isin

In [85]:
mask = np.random.randint(0, 7, 24).reshape((4,6))
mask

array([[3, 0, 4, 5, 6, 3],
       [5, 6, 0, 4, 6, 1],
       [0, 0, 1, 5, 3, 6],
       [4, 5, 4, 1, 0, 1]])

In [124]:
max_sample_n = 5
mask_values = [0,1,4]
mask_bool = np.isin(mask.flatten(), mask_values)
x, = np.where(mask_bool)
idxs = np.random.choice(range(mask_bool.sum()), 
                        size=max_sample_n,
                        replace=False)

selector = x[idxs]
mask.flatten()[selector]

array([4, 0, 4, 0, 0])

In [109]:
x

(array([ 1,  2,  8,  9, 11, 12, 13, 14, 18, 20, 21, 22, 23]),)

[8 7 4 2 1]


array([0, 2, 2, 1, 2])

## Random selection

In [25]:
np.random.choice(range(5), size=5, replace=False)

array([2, 1, 0, 4, 3])

## カラムごとに異なる値を置換

In [226]:
a = np.random.randint(0, 6, 32).reshape((8,4)).astype('float32')
# b = np.array((1, 2, 3, 4))
b = (1, 2, 3, 4)
print(a)
print(b)

[[1. 0. 4. 5.]
 [1. 1. 3. 3.]
 [5. 2. 2. 5.]
 [0. 0. 3. 1.]
 [2. 1. 4. 1.]
 [2. 3. 0. 0.]
 [5. 4. 0. 3.]
 [1. 1. 5. 3.]]
(1, 2, 3, 4)


In [227]:
replace = np.equal(a, b)
replace

array([[ True, False, False, False],
       [ True, False,  True, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True, False, False, False]])

In [228]:
a[replace] = np.nan
print(a)

[[nan  0.  4.  5.]
 [nan  1. nan  3.]
 [ 5. nan  2.  5.]
 [ 0.  0. nan  1.]
 [ 2.  1.  4.  1.]
 [ 2.  3.  0.  0.]
 [ 5.  4.  0.  3.]
 [nan  1.  5.  3.]]


In [233]:
np.nanmean(a, axis=0)

array([2.8      , 1.4285715, 2.5      , 2.625    ], dtype=float32)

In [221]:
a[replace] = (np.tile(np.array(b) * 100,
                      (a.shape[0],1)))[replace]
print(a)

[[  3   1   1   3]
 [  3   1   2 400]
 [  3   3   1   0]
 [  2   0 300   1]
 [100   0   1   2]
 [  5 200   0 400]
 [100   3   5   0]
 [  5   3   0   3]]
